services:
  - type: web
    name: roxi-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --max-request-line 8190 --limit-request-field_size 8190 --limit-request-line 0 --limit-request-fields 0 main:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: roxi-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: roxi-redis
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: "3"
      - key: MAX_CONTENT_LENGTH
        value: "52428800"

  - type: worker
    name: roxi-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A app.celery worker --loglevel=info
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: roxi-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: roxi-redis
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: MAX_CONTENT_LENGTH
        value: "52428800"

  - type: redis
    name: roxi-redis
    ipAllowList: []
    plan: free

databases:
  - name: roxi-db
    databaseName: roxi_production
    user: roxi
    plan: free